
imports: ["../../conf/common.yml"]
loglevel: INFO

serverinfo:
    listen: 0.0.0.0:2000
    checksign: true
    debug: true
    psqlurl: postgres://ybapi:123456@172.17.6.140:5432/ybapi?sslmode=disable
    mqurls: ['172.17.6.140:4150', '127.0.0.1:4152']


redis:
   pub:
    master:
      addr: 172.17.6.140:6379
      password: 123456
      dbindex: 0
      timeout: 10s 

upload:
  image_quality: 70
  bucket: yunbay
  url_prefix: https://file.yunbay.com/

amazon:
  access_key: AKIAIF3M4GI4DWS53NPQ
  secret_key: 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  
  region: ap-southeast-1
ext:


