
imports: ["../../conf/common.yml"]
loglevel: INFO

serverinfo:
 listen: 0.0.0.0:91
 checksign: true
 debug: true
 psqlurl: postgres://ybapi:123456@172.17.6.140:5432/ybapi?sslmode=disable
 mqurls: ['172.17.6.140:4150', '127.0.0.1:4152']
 

redis:
   pub:
    master:
      addr: 172.17.6.140:6379
      password: 123456
      dbindex: 0
      timeout: 10s 
   api:
    master:
      addr: 172.17.6.140:6379
      password: 123456
      dbindex: 6
      timeout: 10s  

ext:
  eos_url: https://jungle.bloks.io/transaction/

orders:
 auto_cancel_time: 5m
 auto_finish_time: 360h

app_cfg :
  "0": ./appcfg.json
  "1": ./appcfg_ch.json

ipipfile: /data/ipipvip.datx
rsapublickeyfile:
rsaprivatekeyfile:

appkeys:
 account: 16c86816ab0cfa1493da230cdf356476
 ybapi: a20331ad70081a25d0b00d0b0052d202
 upload: bc6b7ed67224ea66763f9dfccdfb6cea
 ybasset: 834ea8fafc216b4f63a53cc36ba2888d
 ybproduct: tb9UuBY4GRr89SYzpVthbIF6onliYoyN
 ybgoods: 8bbc65632ed57b1cb64225c331a68739

servers:
 account: http://172.17.6.140:92
 ybapi: http://172.17.6.140:90
 ybasset: http://172.17.6.140:95
 ybproduct: http://product.yunbay.com
 ybgoods: http://172.17.6.140:96

serverhost:
 account: account.yunbay.com
 ybapi: api.yunbay.com
 ybasset: asset.yunbay.com
 ybproduct: product.yunbay.com
 ybgoods: goods.yunbay.com

email:
 fankui: '<p>尊敬的用户您好！</p><div style=\"margin-bottom:50px;\"><p>您的请求反馈已提交！</p><p>我们会及时跟进处理，并通过您的当前邮箱答复您。</p><p>若有疑问可以回复该邮件与YunBay平台运营团队沟通！</p><p>感谢您对YunBay商城的支持!<br/>YunBay 官方<br/><div style=\"color:#8f8f8f;\">------------------------------------<br/>官网：<a href=\"https://www.yunbay.com/\" target=\"_blank\">https://www.yunbay.com</a><br/>服务邮箱：<a href=\"mailto:service@yunbay.com\">service@yunbay.com</a><br/>官方电报群：@YunBay官方中文群</p></div>'

ofpay:
  app_id: A08566
  app_pws: 4c625b7861a92c7971cd2029c2fd3c4a
  app_secret: OFCARD
  # host: http://api2.ofpay.com
  host: http://apitest.ofpay.com
  #app_id: A190521002
  #app_pws: f15a755f9cab9ef7389cf99d76644e31
  #app_secret: 217D53715557D862
  test: true
  ret_url: http://202.104.136.37:2006/v1/of/ret/notify  
  ofcard:
    gdab5: '1711278'
    gdab10: '1711290'
    gdab20: '1711281'
    gdab30: '1711288'
    gdab50: '1711283'
    gdab100: '1711284'
    gdab500: '1711285'
    gdab1000: '1711286'

smstext:
 aftersale: '尊敬的云贝商家，有消费者对您销售的商品发起了售后服务申请，请及时登录云贝官居网联系用户妥善处理。'
 neworders: '尊敬的云贝商家，您有新的订单产生，请及时登录云贝官网处理。'
 lottery_ok: '<div><h1 style="text-align: center;color: red" >恭喜您中了<h1><p>恭喜您中了"<span style="color:red">%v</span>"，请尽快到我的记录里确认订单，以便商家及时为您发货。</p></div>'
 lottery_fail: '<div><h1 style="text-align: center" >sorry!您未中奖<h1><p>很遗憾！您本次参与的"<span style="color:red">%v</span>"未能中奖，请留意其它商品，再接再历！</p></div>'
 