package common

const (
	ERR_FORBIDDEN_COMMENT      string = "ERR_FORBIDDEN_COMMENT"
	ERR_FORBIDDEN_FILM_ARTICLE string = "ERR_FORBIDDEN_FILM_ARTICLE"
	ERR_FORBIDDEN_FILM_LIST    string = "ERR_FORBIDDEN_FILM_LIST"
	ERR_FORBIDDEN_WEMEDIA      string = "ERR_FORBIDDEN_WEMEDIA"
	ERR_FORBIDDEN_COMMENTARY   string = "ERR_FORBIDDEN_COMMENTARY"
	ERR_FORBIDDEN_FILM_DISCUSS string = "ERR_FORBIDDEN_FILM_DISCUSS"
	ERR_FORBIDDEN_MODIFY       string = "ERR_FORBIDDEN_MODIFY"
	ERR_MQ_NAME_NOT_FOUND      string = "ERR_NAME_NOT_FOUND"
	ERR_ENCRYPT_FAILED         string = "ERR_ENCRYPT_FAILED"
	ERR_DECRYPT_FAILED         string = "ERR_DECRYPT_FAILED"

	ERR_ZJPASSWORD_INVALID string = "ERR_ZJPASSWORD_INVALID"
	ERR_PRODUCT_NOT_MORE   string = "ERR_PRODUCT_NOT_MORE"
	ERR_MONEY_NOT_MORE     string = "ERR_MONEY_NOT_MORE"

	ERR_COIN_TYPE_NOT_SUPPORT     string = "ERR_COIN_TYPE_NOT_SUPPORT"
	ERR_CURRENCY_TYPE_NOT_SUPPORT string = "ERR_CURRENCY_TYPE_NOT_SUPPORT"

	ERR_NOT_EXISTS              string = "ERR_NOT_EXISTS"        // 不存在
	ERR_ADDRESS_NOT_EXIST       string = "ERR_ADDRESS_NOT_EXIST" // 地址不存在
	ERR_CARTID_NOT_EXIST        string = "ERR_CARTID_NOT_EXIST"
	ERR_FORBIDDEN_BUY_OWNGOODS  string = "ERR_FORBIDDEN_BUY_OWNGOODS" // 不能购物自己的商品
	ERR_USER_TYPE_NOT_SELLER    string = "ERR_USER_TYPE_NOT_SELLER"   // 非卖家用户类型
	ERR_ORDER_NOT_EXIST         string = "ERR_ORDER_NOT_EXIST"
	ERR_ORDER_AMOUNT_INVALID    string = "ERR_ORDER_AMOUNT_INVALID"
	ERR_ORDER_FORBIDDENT_MODIFY string = "ERR_ORDER_FORBIDDENT_MODIFY" // 订单不允许修改(已经支付)
	ERR_ORDER_HASPAYED          string = "ERR_ORDER_HASPAYED"          // 订单已经被支付
	ERR_ORDER_FORBIDDEN_CANCEL  string = "ERR_ORDER_FORBIDDEN_CANCEL"  // 订单禁止取消
	ERR_ORDER_FINISH_FAILED     string = "ERR_ORDER_FINISH_FAILED"     // 订单完成失败
	ERR_ORDER_FORBIDDEN_DEL     string = "ERR_ORDER_FORBIDDEN_DEL"     // 订单禁止删除
	ERR_NOT_BUSINESS            string = "ERR_NOT_BUSINESS"            // 不是商家
	ERR_BROKER_NOT_EXIST        string = "ERR_BROKER_NOT_EXIST"        // 邀请人不存在
	ERR_BUSINESS_RATE_INVALID   string = "ERR_BUSINESS_RATE_INVALID"   // 商家返现比例不合法

	ERR_NOT_WHITELIST_SELLER string = "ERR_NOT_WHITELIST_SELLER" //非白名单商家
	ERR_WHITELIST_SELLER     string = "ERR_WHITELIST_SELLER"     //不能推荐白名单商家的商铺
	ERR_NOT_WHITELIST_USER   string = "ERR_NOT_WHITELIST_USER"   //非白名单用户
)
